spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hitef?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
logging:
  file: ${wechat.hitef.app-file-path}/log/hitef.%d{yyyy-MM-dd}.log

wechat:
  hitef:
    app-file-path: C:/hitef
    server-domain-url: http://hitef.ngrok.i2it.net
    pay-url: ${wechat.hitef.server-domain-url}${server.context-path}/test/
    certification-path: ${wechat.hitef.app-file-path}/certification
