spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hitef-weixin?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: webuser
    password: L1~dQ4nV5[Y7!Tb]
logging:
  file: ${wechat.hitef.app-file-path}/log/hitef.%d{yyyy-MM-dd}.log

wechat:
  hitef:
    app-file-path: H:/hitef-weixin
    server-domain-url: http://alumni.hit.edu.cn
    pay-url: ${wechat.hitef.server-domain-url}${server.context-path}/donate/
    certification-path: ${wechat.hitef.app-file-path}/certification